### ISSUE TITLE
[Request] Add command for switching tabs

### ISSUE THREAD

**Issue by hunkyburrito** [dedukun/relative-motions.yazi#6]
The keybinds for relative-motions prevent being able to select tabs with number keys (unless I'm missing something). 

It would be nice if there was a command to move between tabs such as a `gt` for go to tab. I would be satisfied with just the ability to switch tabs, but there other possible commands that could be added for tabs like creating, deleting, and swapping. Those commands might be out of scope however.

**Comment by dedukun** [comment]
Hey,

The recommended keybindings for this plugin overwrite the default tab selection keybindings from Yazi, however you can change them to anything that you would like( or use [a key to trigger this plugin](https://github.com/dedukun/relative-motions.yazi?tab=readme-ov-file#configuration)), or alternative you can create new keybindings for the tabs.

If you would like to have `gt1` to change to the first tab you can simply add the following to the `keymap.toml`:

```toml
[[manager.prepend_keymap]]
on = [ "gt1" ]
run = "tab_switch 0"
desc = "Switch to the first tab"
```

Yazi already has the commands that for tabs creation, deletion and swapping, you can check them [in the docs here](https://yazi-rs.github.io/docs/configuration/keymap#manager.tab_create).

Additionally, for reference, you can also check the [default Yazi keybindings here](https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap.toml#L123), there are already default keybinding for creating and swapping tabs.

**Comment by hunkyburrito** [comment]
Yeah, I'm aware of the commands and  keybinding options available in yazi. I am currently using different keybindings for tab switching as well.

I moreso meant implementing relative motions for tab commands. For the creation of tabs for example, you would type `2t` to make 2 tabs.

This all stems from muscle memory I built using vim browser plugins, so I do understand that it may be too niche of a feature to implement.

**Comment by hunkyburrito** [comment]
Ideally at least the keybinds could be modular since they're subjective. 

As for ideas for keybinds, here's a few:
- `#t` create # tabs
- `#H` / `#L` move left / right # tabs
- `#gt` go to tab #
- `#w` close tab #
- `#W` close # tabs (right)
- `#<` swap current tab with # tabs left
- `#>` swap current tab with # tabs right
- `#~` swap current tab with tab #

**Comment by dedukun** [comment]
I've implemented the features in PR #7, can you test it to make sure everything is correct?

It's all hard coded at the moment, I'll refactor the code in a following PR to make it possible to remap the keybindings

**Comment by hunkyburrito** [comment]
Looks good to me! The `#W` command works a little differently from how I was expecting, but I'm honestly fine with how it works right now too.

The way I was expecting it to work was to close a number of tabs starting from the current tab. Similar to the `#L` command but closing the traversed tabs instead.

**Comment by dedukun** [comment]
I've updated the PR with the behavior like you described, let me know if it's as you expected.

If you prefer the old way it was working I can revert it back, or we can have both behaviors and add one of them to another key.

**Comment by hunkyburrito** [comment]
Yup, works like I was expecting. Nice work!

**Comment by dedukun** [comment]
Goods, let's merge it them.

Thanks for the suggestion and for testing.
